### ISSUE TITLE
Kecleon's shop sells out when loading a save file

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#1]
Steps to reproduce:
1. Visit any dungeon and leave
2. Go to Kecleon's shop, see that there are items
3. Save and quit, then reload the save
4. Visit Kecleon's shop. All the items will be sold out

**Comment by audinowho** [comment]
Issue found in RogueEssence.
Fix commit: https://github.com/RogueCollab/RogueEssence/commit/20213fe3f5c5de34b564ccda9bd1797e80e04651
