### ISSUE TITLE
Windows, Linux, and Mac "builds" attached to patchnotes do not contain a working copy of the game

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#100]
The pre-zipped Windows, Linux, and Mac files attached to the patchnotes do not contain working copies of the game; they are missing all of the game content and data and thus do not run. As this is the usual method of distributing a pre-compiled program on Github, this can give visitors a false impression that they simply need to download one of these files to play the game.

## Proposed remediations
* Remove the zip downloads from the patchnotes entirely and direct potential players to our Discord where they can download the updater.
 * Additionally, I am told that combination installer/updater programs are often called "setup" programs, e.g. "PMDOSetup.exe". It would be good to make this name change to better illustrate that the program also installs the game to a first-time user.
* Alternatively, add the missing asset and script files so that the zip downloads contain full working copies of the game.

**Comment by audinowho** [comment]
Resolved as of https://github.com/audinowho/PMDODump/releases/tag/v0.5.14.1
