### ISSUE TITLE
Closing the game during the recruitment can descync the quicksave.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#115]
I don't know much details of what exactly happened but i managed to do destroy my quick save doing it.
[data.zip](https://github.com/audinowho/PMDODump/files/8931330/data.zip)
this file contains a video from real game perspective and the final result of the give up replay.

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/commit/ffe2b316ac6fbedcc0170b46492a4f701116836e
