### ISSUE TITLE
Stacking weather in ground map editor

### ISSUE THREAD

**Issue by Greenjoe12345** [audinowho/PMDODump#12]
so if map scripts are edited while the map editor is open, weathers will stack on top of one another
how to reproduce
load the ground map
go into edit mode
edit the script to change weather
reload scripts though the scripts tab of the ground map editor
save and tested
that got the first weather in place
go into edit ground again
edit the script to change the weather again
reload scripts through scripts tab of ground map editor again
save and test map
weathers now stacked

**Comment by audinowho** [comment]
Fixed as of https://github.com/RogueCollab/RogueEssence/commit/b8d0bda0ecab3a47e613402ab4187fa62e7d073e
planned for 0.5.7.0 release.
