### ISSUE TITLE
Option to clear replay data

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#126]
it would be nice to have a option to wipe the folder where the replays are saved, i have to manually visit this folder to clear all the replay data present there. (you could add this option here)
![image](https://user-images.githubusercontent.com/6380147/175748872-966e7b75-f831-4d33-b482-47554d767811.png)

I do that around 1 up to 3 times per week, and i don't have the patience to remove it one by one via in game interface.

**Comment by audinowho** [comment]
Make this an option in the settings to set a maximum number of replays stored before the game automatically removes the older ones.  Also give the player the option to fave a replay so that it does not fall under the removal policy.

**Comment by audinowho** [comment]
Code for moving completed games into replays is here: https://github.com/RogueCollab/RogueEssence/blob/adecdc6cec7dab4c9051ee44c3e323411f5dde44/RogueEssence/Data/DataManager.cs#L1198
Options code is here (probably put it next to the window choices): https://github.com/RogueCollab/RogueEssence/blob/adecdc6cec7dab4c9051ee44c3e323411f5dde44/RogueEssence/Menu/Settings/SettingsMenu.cs#L57

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/pull/11
