### ISSUE TITLE
Feature request: show floor number of clear for dungeons with multiple exits

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#127]
e.g. Secret Garden. When viewing a replay, I can see the player cleared the dungeon, but not how far they made it in total. Did they clear on 29F? 30F? 31F? The only way to find out presently is to play back the replay, which can take a long time.

**Comment by audinowho** [comment]
To address this issue, I will add a floor traversal history to the ending info, as this will become more complicated with branching dungeons and secret detours.

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/commit/c6c4d2ea36fc656050626c76a647f9c777688302
