### ISSUE TITLE
Feature request: fast way to verify no desync issues with replays

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#128]
I would like to allow runs with minor mods such as Gender Unlock onto the leaderboards. Presently, the only way I have to verify a replay will play back correctly with no desyncs is to play it back, which can take a long time even at the highest speed.

As I understand it, the code that loads quicksaves essentially plays back a replay as fast as possible. I would like to be able to do this to arbitrary replays to quickly verify that they do not contain desyncs due to mods, bugs, or other issues.

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/pull/19
This PR will enable the option in dev mode.  If the replay completes without fail, it is considered legitimate.  Any dev tool usage will ruin the integrity of the replay and cause it to desync or error by default.
