### ISSUE TITLE
Poison Rework Considerations

### ISSUE THREAD

**Issue by audinowho** [audinowho/PMDODump#129]
Umbrella issue for changing the way Poison works.

The design goal of Poison:
-To punish aggression and exertion for players, forcing them to lay low while the status is present.
-When inflicted on enemies, it is meant to supplement enough damage to be worth using on defensive mobs or bosses.

Current issue:
The status's permanence can result in an ended floor exploration with no lum berry on hand.
On-attack trigger makes it a less appealing source of damage when running away.

Potential changes:

Only when attacking:
-Poison deals 1/8 damage when attacking, but cannot KO.
-Poison deals 1/8 damage when attacking, but wears off after 50 turns.
-Poison deals 1/8 damage and increases duration by 10 when attacking, but wears off after 50 turns.

Damage every turn, worsened by attacking:
-Poison deals 1/16 damage at the end of every turn, increases duration by 2 when attacking, wears off after 5 turns.
-Poison deals 1/16 damage at the end of every turn, also does 1/16 damage when attacking, wears off after 5 turns.
-Poison deals 1/16 damage at the end of every turn, also does 1/16 damage and increases duration by 1 when attacking, wears off after 5 turns.

**Comment by Xindage** [comment]
i'll just put a note here about one thing that you all don't consider, it's the regeneration blocking, abilities that negate effects of poison should not block regenerating. a great example is poison heal gliscor and maybe magic guard since it block all inderect effects, so it should not prevent me from healing(this one we can discuss about).

**Comment by audinowho** [comment]
https://github.com/audinowho/PMDODump/commit/c42cef96844e8205e6eb4b8b4ca85f0a7c2c66d0
https://github.com/audinowho/PMDODump/commit/55270028a96bff15fa091cd14533bccd07af8af2
