### ISSUE TITLE
Ask player for confirmation when loading with missing mods

### ISSUE THREAD

**Issue by audinowho** [audinowho/PMDODump#13]
Steps to set up scenario:
A player plays the game with mods A, B, and C.
Player saves the game.
Player turns off Mods A and C.
Player loads the game.

Expected behavior:
Game asks for confirmation: "Are you sure you want to load this save without these mods?"
Make sure it shows a list of missing mods when it does this.

**Comment by Shitpost-Sunkern** [comment]
Note that there might not necessarily be an issue with removing certain mods at certain times, and it may be helpful to have a mechanism to check for this as well. Nemo the Axolotl's [Gauntlet Cave](https://www.dropbox.com/s/e4qgg8xwygta6tl/Gauntlet_Cave.zip?dl=0), for instance, has no compatibility issues when being removed as long as the player isn't quicksaved inside of the dungeon at the time.
