### ISSUE TITLE
Field effect applyes this layer twice.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#135]
Off-topic: learn to stop using Alt+Enter in github, that's why i posted a blank issue.

The effects like sandstorm and electric terrain apply its layer effect twice after some turns, its very noticeable:
![image](https://user-images.githubusercontent.com/6380147/180662338-7cb7390d-7c3e-4b96-a980-a98eaa389a78.png)
I dont know if it happen with other effects too but so far these 2 indeed do this.

**Comment by Xindage** [comment]
[2022-07-24_08-13-08.rsrec.zip](https://github.com/audinowho/PMDODump/files/9227753/2022-07-24_08-13-08.rsrec.zip)
here's the replay of this happening, pay attention in the first floor of this area (3th area of secret garden).

**Comment by audinowho** [comment]
This does not appear to show up in replays.  It is likely reproducible but will need a live situation of some sort.

**Comment by audinowho** [comment]
fixed in https://github.com/RogueCollab/RogueEssence/commit/bf8c4f589c4caffe79fb16b880add8d50297838d
