### ISSUE TITLE
Favorite pokemons has no priority in the assembly list anymore.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#140]
As the title says now the last pokemon used last in party is now placed in the first place in the list, it's just acting differently from what it was before.
![image](https://user-images.githubusercontent.com/6380147/183268141-d7aeb18b-0158-41b3-b1db-21db1c1a1136.png)

**Comment by audinowho** [comment]
Fixed in https://github.com/RogueCollab/RogueEssence/commit/3e175c9224f373c1267fc1a69a1cef8e6d44c7cb
Save files that have the problem will need to favorite all out-of-order recruits and then unfavorite them again.
