### ISSUE TITLE
[Feature Request] Boss Health Bar

### ISSUE THREAD

**Issue by AlexanderGroeger** [audinowho/PMDODump#15]
Boss fights do not feature health bars. It would be helpful to the player if these existed that way they can gauge how much longer the fight will last and act accordingly.

**Comment by Palikadude** [comment]
Can't you just hold the button that lets you face different directions to see how much health the enemy has left?

**Comment by AlexanderGroeger** [comment]
I didn't realize that was a thing. Thanks. It appears to function well; although it doesn't give the same feel as a proper boss HP bar would. Additionally, there are no numerical values attached to the HP bar.

**Comment by Palikadude** [comment]
I think it's generous enough you can see an HP bar at all, you shouldn't be able to get detailed info about your opponent just by looking at them

**Comment by audinowho** [comment]
S-Button health bar will suffice for this purpose.
