### ISSUE TITLE
Request: Mob attribute that prevents using moves if certain distance from player/ally.

### ISSUE THREAD

**Issue by Palikadude** [audinowho/PMDODump#155]
It would be nice to give moves like growl or curse to enemy mons without having them spam it constantly as soon as they come on screen. It can also be imbalanced to have this because say I want to give Curse to a Onix; it's going to spam it before you can even get in range and suddenly it's a huge problem to deal with. I suggest adding a mob attribute similar to weak or moves off that prevents them from using attacks if more than a specified tiles away from a player or an ally.

**Comment by audinowho** [comment]
https://github.com/audinowho/PMDODump/issues/199
