### ISSUE TITLE
Request: Summary for Spawn chances in editor, allowing for editing of existing weights

### ISSUE THREAD

**Issue by Palikadude** [audinowho/PMDODump#161]
![image](https://user-images.githubusercontent.com/21061217/185687077-9c7e3210-6481-4931-9009-265fda2e369c.png)

It would be useful to include a summary of sorts or an option to see a summary of category spawn chances as well as overall individual item spawn chances

I would also like to add that some steps, such as defining item grouping weights and the floors they apply to can't be edited, and need to be deleted and added back again to bring up the menu to adjust starts and ends. Please allow it so they can be modified without having to be deleted and recreated.

**Comment by audinowho** [comment]
Added in https://github.com/RogueCollab/RogueEssence/commit/17b0cbe339ef1a0d038d6163b00af596603e1bd6 and https://github.com/RogueCollab/RogueEssence/commit/cca6deb93a5f8245ad086c21bb3bfa569974d5bb
