### ISSUE TITLE
Request: CharPoseAnim arbitrary animation frame

### ISSUE THREAD

**Issue by Palikadude** [audinowho/PMDODump#162]
Currently, CharPoseAnim plays an animation then freezes on the last frame of it. Please either enhance this function or add a new one that sets a character's animation to a given frame without any animation leading up to that frame. This will be useful for things such as trembling (pmd2 sets first frame as walking for some trembling animations on top of the shake effect), or for other random things that may come up in the future

**Comment by audinowho** [comment]
Added ground action FrameGroundAction to do this.  An example of of this can be found in the new script:
https://github.com/audinowho/DumpAsset/blob/7a39cc7692973a6667b606fac65f7d27b0cf6a8f/Data/Script/ground/test_grounds/init.lua#L306
commit: https://github.com/RogueCollab/RogueEssence/commit/449351fd68d7cdf2bd647f4b6369353778f660af
