### ISSUE TITLE
MobSpawnAltColor with chance of 0 causes half shininess

### ISSUE THREAD

**Issue by Palikadude** [audinowho/PMDODump#163]
![image](https://user-images.githubusercontent.com/21061217/185728968-d2e56f60-88d9-4247-92ff-aaf98ba41a3f.png)

Mobs in the wall monster house are set to a alt color chance of 0 with the intention of making it so they can never be shiny. However, mobs still seem to be marked as shiny with a star in message logs despite not being shiny in color, not shining upon entry w/ sfx, nor being purple on the minimap.

**Comment by audinowho** [comment]
Fix in https://github.com/PMDCollab/PMDC/commit/fdb500e80b301f9e7e0ade47fcde4739bd5c3e0b
