### ISSUE TITLE
Hidden power typeless error

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#164]
Hidden power sometimes work as typeless and causes a error.

Following the debug message:
2022/08/20 15:24:58.908] Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Exception Depth: 0
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at PMDC.Dungeon.HiddenPowerEvent.Apply(GameEventOwner owner, Character ownerChar, BattleContext context)+MoveNext()
   at RogueEssence.Coroutine.MoveNext()

Lua Trace:
stack traceback:

Coroutine Trace:
PMDC.Dungeon.HiddenPowerEvent+<Apply>d__2
RogueEssence.Dungeon.Character+<OnAction>d__161
RogueEssence.Dungeon.DungeonScene+<ExecuteAction>d__11
RogueEssence.Dungeon.DungeonScene+<CheckExecuteAction>d__9
RogueEssence.Dungeon.DungeonScene+<ProcessUseSkill>d__1
RogueEssence.Dungeon.DungeonScene+<ProcessInput>d__111
RogueEssence.Dungeon.DungeonScene+<ProcessPlayerInput>d__110
RogueEssence.Dungeon.DungeonScene+<ProcessInput>d__181
RogueEssence.Dungeon.DungeonScene+<ProcessInput>d__180
RogueEssence.GameManager+<ScreenMainCoroutine>d__71

**Comment by audinowho** [comment]
Happens due to an off-by-one error.  Fixed in https://github.com/PMDCollab/PMDC/commit/ae7762c6da60e8b39216391e8d417ebc85e37afe#diff-10fbc64e8690c294268c713cd6b05f71ddc6957b42bf7b051a0dd38ca2008704L6685
