### ISSUE TITLE
Opponent pokemon blocking each other movement.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#166]
Enemies pokemons seems to block each other path and they start to just stand still in the place, it can cause some "unbalance".
It's very noticeable in Secret garden while using X-Ray specs.
Notice this group of five pokemons,
![image](https://user-images.githubusercontent.com/6380147/185761755-2d79f938-e676-4613-afd5-932dbcd44b96.png)
They all turn up to my direction when i get close.

**Comment by audinowho** [comment]
fix in https://github.com/PMDCollab/PMDC/commit/4722a49b64817aab9da881128db78a3a5d1f4a24
