### ISSUE TITLE
Unable to clone due to missing RawAssets submodule

### ISSUE THREAD

**Issue by FlarosOverfield** [audinowho/PMDODump#167]
![image](https://user-images.githubusercontent.com/24918282/185863669-33ab14f1-4b48-43c8-9fb8-ebcf2b071dd0.png)
This is caused by [RawAsset @ fa9ab1b](https://github.com/PMDCollab/RawAsset/tree/fa9ab1b4d7cd8428ece4ce8f1a4b3556bee51484) pointing to a 404.
![image](https://user-images.githubusercontent.com/24918282/185864135-d6ab2ede-de93-4970-92f9-b302d70c3b55.png)

**Comment by audinowho** [comment]
Added with https://github.com/PMDCollab/RawAsset/tree/fa9ab1b4d7cd8428ece4ce8f1a4b3556bee51484
