### ISSUE TITLE
Progress bar for updater download

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#17]
Exactly what the title says: a progress bar letting the user know how much of the ZIP file has been downloaded during update. Presently, there is no user feedback as to what the updater is doing during that stage, thus making it impossible to tell whether the program has halted or if the download is taking a while due to a slow internet connection.

**Comment by audinowho** [comment]
https://github.com/audinowho/PMDODump/commit/67e444ca9e20b5256aadfbc66686757add939787
