### ISSUE TITLE
View Move Learnset In-Game

### ISSUE THREAD

**Issue by thebalker** [audinowho/PMDODump#176]
Being able to see the future prospects of team members would be nice so you can know ahead of time whether it's worth keeping team members around, or what stage of the game they're most using for. The list of moves learnable by level-up being visible on an extra page or two in the Summary would help with this, and ideally information on each move could be pulled up from this menu.

**Comment by audinowho** [comment]
The evolution menu can be used as a starting point:
https://github.com/RogueCollab/RogueEssence/blob/adecdc6cec7dab4c9051ee44c3e323411f5dde44/RogueEssence/Menu/Team/MemberFeaturesMenu.cs

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/commits/master
