### ISSUE TITLE
Auto-turn is slow to activate after an action

### ISSUE THREAD

**Issue by thebalker** [audinowho/PMDODump#184]
After the end of a turn, there is a brief period of time where pressing the turn button won't auto-turn the leader to the nearest enemy.

https://user-images.githubusercontent.com/112437907/187811142-634644a7-18dd-4226-a4b5-7a3ee7a015c5.mp4

Sometimes, it can even take multiple presses of the turn button to get auto-turn to work. In the image below, it took 3 presses of the turn button to get auto-turn to work (player pikachu, ally budew, enemy caterpie)

![image](https://user-images.githubusercontent.com/112437907/187811478-32b59369-ea54-477d-9770-85598534bcf4.png)

**Comment by audinowho** [comment]
Relevant code here: https://github.com/RogueCollab/RogueEssence/blob/adecdc6cec7dab4c9051ee44c3e323411f5dde44/RogueEssence/Dungeon/DungeonScene.cs#L503
Cause: code looks for a button down to initiate the turn.  if the player pressed the turn button during actions when inputs aren't being taken, the "JustPressed" will be missed and will not cause the turn.

The second part is intended behavior: pressing turn multiple times will cycle through all possible targets in line of sight.

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/pull/26
