### ISSUE TITLE
Crash when attempting to load debug zone with F12 on 0.6.3

### ISSUE THREAD

**Issue by FlarosOverfield** [audinowho/PMDODump#186]
```
[2022/09/11 11:50:54.304] [SE]:LuaEngine.RunZoneScript(): Error running zone script!:
cannot open Z:\PortableApps\PokemonMysteryDungeonOrigins\PMDO\Data\Script\zone\debug\init.lua: No such file or directory
path:
Z:\PortableApps\PokemonMysteryDungeonOrigins\PMDO\Data\Script\zone\debug\init.lua
```
This is caused by the engine attempting to load zone\debug, when it should load zone\debug_zone.

![image](https://user-images.githubusercontent.com/24918282/189521511-2a0e5e46-b245-4d73-a102-e2d6ba506239.png)

**Comment by audinowho** [comment]
Found to be an issue with startermod, fixed in https://github.com/audinowho/DumpAsset/commit/22858838dd27e4ce69b24a7d8f8795b5ce32cbd8
