### ISSUE TITLE
Ground mode TM use always targets leader with learnset of party members

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#19]
This enables Pokémon to learn TM moves that aren't necessarily part of their TM learnset.

Steps to reproduce:
1. Start with a TM (for example, Flamethrower) and two party members: one who can learn the TM move (for example: Charmander) and one who cannot (for example: Starly)
2. Set the party member who cannot learn the move as the team leader.
3. Open the Items menu and use the TM on the party member who can learn the move.
4. The TM will attempt to teach the move to the party leader, even though that Pokémon should not be able to learn the move.

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/commit/079e693b157e73f516eaf6914ed58a789d2f2ec9
