### ISSUE TITLE
Belly of all party members depletes while exploring

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#2]
All party members' Belly will deplete at the same time while exploring.

Steps to reproduce:

1. Enter a dungeon with multiple party members
2. Walk around the floor for a while
3. Open the menu. See that the Belly of party members who are not the leader has depleted.

**Comment by audinowho** [comment]
Resolution in submodule:
https://github.com/RogueCollab/RogueEssence/commit/1d4a692382cbfd912b55412c771b9fc4ae31a11f
