### ISSUE TITLE
opening vaults in SH gives a error

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#223]
![image](https://user-images.githubusercontent.com/6380147/217965237-60d0b761-5797-46d7-bd14-6010fb64ca41.png)
[2023/02/09 20:52:13.77] The given key 'PMDC.Dungeon.DangerState, PMDC, Version=0.6.9.0, Culture=neutral, PublicKeyToken=null' was not present in the dictionary.
Exception Depth: 0
System.Collections.Generic.KeyNotFoundException: The given key 'PMDC.Dungeon.DangerState, PMDC, Version=0.6.9.0, Culture=neutral, PublicKeyToken=null' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RogueElements.TypeDict`1.Get[TK]()
   at PMDC.Dungeon.OpenOtherPassageEvent.Apply(GameEventOwner owner, Character ownerChar, SingleCharContext context)+MoveNext()
   at RogueEssence.Coroutine.MoveNext()

Lua Trace:
stack traceback:

Coroutine Trace:
PMDC.Dungeon.OpenOtherPassageEvent+<Apply>d__8
RogueEssence.Dungeon.EffectTile+<InteractWithTile>d__27
PMDC.Dungeon.KeyUnlockEvent+<Apply>d__2
RogueEssence.Dungeon.Character+<HitTile>d__167
RogueEssence.Dungeon.BattleContext+<ProcessHitTile>d__72
RogueEssence.Dungeon.DungeonScene+<ProcessHitQueue>d__28
RogueEssence.Dungeon.DungeonScene+<ReleaseHitboxes>d__27
RogueEssence.Dungeon.DungeonScene+<ReleaseHitboxes>d__26
RogueEssence.Dungeon.AttackAction+<ReleaseHitboxes>d__10
RogueEssence.Dungeon.Character+<PerformBattleAction>d__216
RogueEssence.Dungeon.DungeonScene+<PerformAction>d__7
RogueEssence.Dungeon.DungeonScene+<ExecuteAction>d__11
RogueEssence.Dungeon.DungeonScene+<CheckExecuteAction>d__9
RogueEssence.Dungeon.DungeonScene+<ProcessUseItem>d__2
RogueEssence.Dungeon.DungeonScene+<ProcessInput>d__112
RogueEssence.Dungeon.DungeonScene+<ProcessPlayerInput>d__111
RogueEssence.Menu.MenuManager+<processInternalCoroutine>d__46
RogueEssence.Menu.MenuManager+<ProcessMenuCoroutine>d__17
RogueEssence.Menu.MenuManager+<ProcessMenuCoroutine>d__16
PMDC.Dungeon.AskUnlockEvent+<giveLockedResponse>d__3
RogueEssence.Dungeon.DungeonScene+<ProcessInput>d__187
RogueEssence.GameManager+<ScreenMainCoroutine>d__73

**Comment by audinowho** [comment]
PMDC/Dungeon/GameEffects/SingleCharEvent.cs
