### ISSUE TITLE
Extra custom save support

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#224]
I would like to have option to play certain mods with a custom save, right now its possible to do this using dev menu and loading the mod by there, because if you load the mod by the game manager it load your default save with it:
Context on why i would need it: You know that i've been working with the randomizer mod, and i dont want to include illegal pokemons in my main save/rogue so using the save method works well for that situation. but loading -dev to do it is not cool.

**Comment by audinowho** [comment]
Quests load mods with separate save files.  The mod can be changed to a quest to allow a new save, even if the quest itself changes nothing and asks the player to go through the same dungeons.
