### ISSUE TITLE
(Feature request) [Updater] Allow an option to download only.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#236]
in my case that i have to manage internet because i have a limited connection, it would be nice to just download the update files without actually updating.
this would be necessary to adding a extra option on updater to just download the data and then i would need to run it again to apply the changes.

New opition: Check and download update. (Dont update)
check if there's already pending updates, if not allow this option to be available, if not else:
Else option: Apply pending update.
if cheking of pending data is true allow the user to apply it using the update, replacing the option above.

This would be really nice for me.

**Comment by audinowho** [comment]
Not supported, but added instructions in wiki: https://wiki.pmdo.pmdcollab.org/Manual_Install
