### ISSUE TITLE
Feature Request: Option to restart a roguelocke

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#27]
Sometimes it's annoying to have to manually select the same character in the rogue over and over and over again.
A option to restore the last roguelocke would be appreciated in the menu, where it's list located the new, load and info:
.-------------------------,
|New Game
|Load Game
|Restart Last Game
|Info
'-------------------------'

Selecting Restart should give the following options:
Seed: Allow use of 2 options Random / Repeat. (random should be displayed by default if player haven't selected one before, repeat should be used if player repeated a seed before, or used a pre-determined seed in a previous game
Team name: If not set before uses random
Pokemon: Appear only if a repeat seed is selected, place last chosen pokemon overriding if random pokemon was chosen but allow random if the player want to repeat the same seed with a random pokemon.
Char name: Same as the before, blank if none was chosen previously.
them pressing enter tell that you accept the following options and start the game as the last used pokemon (or not if players want to use the same seed with other pokemon).

This can really speed up doing roguelockes when the pokemon list is huge and your pokemon must be searched in the list.

Edit let me know here if you want to suggest something different or if i forget something i'm all ears.

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/pull/31
