### ISSUE TITLE
Some text are wrong for detail means

### ISSUE THREAD

**Issue by Feishiko** [audinowho/PMDODump#349]
The menu has a selection named "Roguelocke", I think if it replace to "Roguelike" is more correct?
![HT01E4Z9}2L2N@}CHB_V{PT](https://github.com/audinowho/PMDODump/assets/54055667/519d22cd-1769-44ee-821b-51e033d0f058)

**Comment by AntyMew** [comment]
This is an intentional play on words with roguelike and nuzlocke
