### ISSUE TITLE
Leech Seed Persists After Death

### ISSUE THREAD

**Issue by bluehar** [audinowho/PMDODump#400]
This happens often in Sickly Hollow, an enemy that has a leech seed dies, but it's leech seed doesn't get removed, and the Pokemon still takes damage every turn.

**Comment by audinowho** [comment]
Can't reproduce.  Please attach a replay.

**Comment by bluehar** [comment]
[untitled.tar.gz](https://github.com/audinowho/PMDODump/files/13762703/untitled.tar.gz)

**Comment by audinowho** [comment]
Intended behavior. Leech Seed always persists until there are no foes to give the HP to.  Defeating the one that used it only works if it's the last opponent.  This can also be found in the status condition's description.
