### ISSUE TITLE
Bug: TM wont apply correctly.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#58]
Using TM in overworld after you moved your moves in the list cause it to be applied in the wrong slot temporally until you enter and quit any dungeon, this is kinda buggy. i have recorded a video to explain that better, notice the Helping hand.
[TMbehaviour.zip](https://github.com/audinowho/PMDODump/files/8287777/TMbehaviour.zip)

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/commit/2a9a3ea832c5c634e37b89702c57f72a3e8e0bdc
