### ISSUE TITLE
Replay test zone RNG wont change.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#59]
Dont matter if you beat it, lose it or escape it, the RNG wont change, it's always the same layout, same items locations and mobs that appear, this can be abused to grind when you know the location of every dragonair.
[2022-03-18 22-36-02.zip](https://github.com/audinowho/PMDODump/files/8308399/2022-03-18.22-36-02.zip)
Please dont watch it if you dont want spoilers...
Note: for example if you get a unlucky seed you can go in any deungeon, load it, give up andf them go again in replay test zone to see if you get more lucky spawn that time.

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/commit/de3838526bb044f017f6c34d68631ded12853b4e
