### ISSUE TITLE
[Feature Request] Looping sound effects for ambiance

### ISSUE THREAD

**Issue by UberNooga** [audinowho/PMDODump#61]
Requesting the ability to make looping sound effects for things like background rain etc. if one wanted to also play music over the top of it, so ambiance doesn't cut out as soon as music plays. 

Could be scripted by adding an argument to the existing SOUND:PlaySE function to allow looping, e.g. SOUND:PlaySE("Rain", true) where "true" means "loop this sound", could be deactivated by setting that to false or making a function to terminate the sound player at that point (latter might be a better solution so you don't have to wait until the end of a loop to stop playing sounds: like a "SOUND:StopSE" or "SOUND:FadeSE" for fadeouts or something).

**Comment by audinowho** [comment]
Added in https://github.com/RogueCollab/RogueEssence/commit/914c43185012693478e4ab06cc9391ad5d0cf37f
Ex
SOUND:LoopSE("Battle/EVT_Applause")
SOUND:LoopBattleSE("EVT_Applause")
SOUND:StopSE("Battle/EVT_Applause")
SOUND:StopBattleSE("EVT_Applause")
