### ISSUE TITLE
Freezing mechanic is not fair to player's side

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#62]
The actual behavior of freezing is unfair to player side in the thawing process.
When the enemy is about to thaw you must stay at least 1 tile away for it because he'll have a turn to do whatever he want.
When we are about to trawl we simple just lost the pokemon's turn and nothing can be done about it, and depending on situation we can just be frozen again.
![image](https://user-images.githubusercontent.com/6380147/159187173-0bbf4019-2cb0-4878-b403-c362dda827fb.png)
This mechanic should be the same for both sides so it can be fair.

**Comment by audinowho** [comment]
Fix in https://github.com/PMDCollab/PMDC/commit/cb705f34077aca3b47ccb403c3299dc5a2a4ea25
