### ISSUE TITLE
Suggestion: Possible real Y and Z specs

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#63]
X-Ray specs allow you to know monsters location so far, but there's no other specs to do different task like seeing interactive tiles and items, no why not create a real Y and Z specs for that task.
Here's the examples:
Y-Ray Specs: A held item that enables the Pokémon to see items through heavy darkness.
(Reveal blue spots on auto map where all items are *except the ones in walls)

Z-Ray Specs: A peculiar held item that allow the Pokémon to sense and know the location of any traps *and items buried inside walls.
(This item should reveal all trap tiles and already display them in automap so the player already know the location of them including wonder tiles, since it's not a strong item alone it can be used to also spot secret items in walls or if not possible allow see the layout of the floor. This item MUST not reveal stairs otherwise it would be very op)
Secondary description: A peculiar held item that allow the Pokémon to know the layout of the dungeon and sense the location of any traps within.

About *s maybe that could be hard doing that in code side so you can ignore or change it at your will
So what you think about it?

**Comment by Shitpost-Sunkern** [comment]
The Y-ray specs are actually an item in Explorers of Sky — they are a negative item that removes information from the map, and inflicts Blinker on anyone being controlled by the AI.

**Comment by audinowho** [comment]
These effects will be covered between Pokemon-specific items and the added Goggle Specs
