### ISSUE TITLE
bug: Yanma behave oddly when facing ghost types

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#64]
Yanma AI just fail to work when it's against ghost types, it does not attack and keep moving back and forward in same turn.

**Comment by Xindage** [comment]
sorry for being a meme but that's the video showing the yanma bug.
https://user-images.githubusercontent.com/6380147/175182262-becc41bf-a9cc-4993-87ae-38f7f08d1463.mp4

**Comment by audinowho** [comment]
fix in https://github.com/audinowho/PMDODump/commit/c082f85c3a1fbfd4dc2ad660b2a25d7015ea9b2f
