### ISSUE TITLE
Request: Debug overlay should include current camera coordinates even when not in camera mode

### ISSUE THREAD

**Issue by Palikadude** [audinowho/PMDODump#65]
Currently debug overlay doesn't include camera coordinates unless I press f9. This wouldn't be an issue, but f9 causes the camera to center on my character, so I can't determine where the camera is exactly using debug info. It would help me when making cutscenes to get the current location of the camera.

**Comment by audinowho** [comment]
Added in https://github.com/RogueCollab/RogueEssence/commit/6ea771a3f134b00b983e0ac1f496bbbeafa2e821
