### ISSUE TITLE
Female is no more a option in roguelocke

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#69]
**MUST NOTE: Female wild pokemon dont appear anymore as well.**

Maybe the recent changes in gender data caused trouble in the code of roguelocke and female choice is no longer select-able, just male or random.
![image](https://user-images.githubusercontent.com/6380147/162588921-d85981e4-4305-4351-8f3b-41fb03cbdf0d.png)
note this also effect to add male on female-only and genderless Pokemon to be male as well

**Comment by Shitpost-Sunkern** [comment]
The issue seems more severe than this — there are no female or genderless wild Pokémon either.

**Comment by audinowho** [comment]
Fix in https://github.com/audinowho/DumpAsset/commit/1c983946f775eff6c217f5f70a46fb6f4161884b
