### ISSUE TITLE
Feature Request: Default Dont use moves option.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#70]
(sorry accidental alt+Enter created the issue instantly)
I want a option to disable teammate from using moves as default at recruitment (at the start would be even better) i hate that every new game after recruiting a pokemon i have to go manually disabling my pokemons from using moves.
because if i forgeot, well he'll start to use moves that is not really usefull right now, but i need to save for later, like helping hand, it's just a waste of pps.

please consider this and again sorry for alt+enter this issue....

**Comment by audinowho** [comment]
Added in https://github.com/audinowho/PMDODump/commit/246bce841e4a0a568d14eae72b8d18c09d27ebc4
