### ISSUE TITLE
Random errors during game leaded to black out.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#74]
While i was playing here, i decided to leave one of my members behind on a stair and move with vaporeon away down to the switch, but on a certain point the game flood on repeatedly with errors unyil it black out.
From what i was able to read it seems to be a bug with "Field of View" or something related.
note: you can resume the game if you move south as soon the quicksave resumes to game mode as seen here:
![image](https://user-images.githubusercontent.com/6380147/164873978-c4a15628-bf71-47d3-b70d-67fbbe4b16fb.png)

Fault save and log:
[2022-04-22_23-34-45.rsqs.tar.gz](https://github.com/audinowho/PMDODump/files/8546090/2022-04-22_23-34-45.rsqs.tar.gz)
[2022-04-23.tar.gz](https://github.com/audinowho/PMDODump/files/8546091/2022-04-23.tar.gz)

Can i bet that happens just because how my beautifly is positioned while my team in far south?

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/commit/0139b118539c5e4538efbd9c447b3c381c4afb08
