### ISSUE TITLE
Improvement: Pouce wand dont reveal the path on use.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#75]
Using pounce wand in a very far location make you go to that spot without revealing anything along the way.

It's a little strange to see your character to slide into the "void" and them out nowhere appear on the end of the path. in my gaming point of view your character should be able to reveal the path as they can see "all-around".

we can choose 3 options:
1- Reveal the path along the way while player is pulled to the end of pounce.
2- Turn player into a magic ball as they go. that can explain some kind of blindness effect.
3- Do nothing, it's not really an issue.

**Comment by audinowho** [comment]
1 was tried in a branch, but it turned out to be a rather hard-to-maintain approach (https://github.com/RogueCollab/RogueEssence/tree/VisionTrail)
Currently, just accepting this as a minor quirk of the engine.
