### ISSUE TITLE
Bug: Pass Scarf wont pass damage to adjancent enemies pokemons

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#76]
Pass scarf is somewhat bugged, it pass the attack from your pokemon to adjacent enemies as intended  but it cause no damage.
Passing attack on enemies:
![image](https://user-images.githubusercontent.com/6380147/165331738-8449ba98-e1b1-45fd-8b4a-41b6e3c2cbd5.png)
Passing attack to allies:
![image](https://user-images.githubusercontent.com/6380147/165331862-f26d7a67-e642-4011-ace7-c50f47b07994.png)

**Comment by audinowho** [comment]
Due to a bug with battle data not being changed to allow hitting allies (from enemy -> other enemy), and BattleContexts not being propagated between functions.  Fix in https://github.com/RogueCollab/RogueEssence/commit/5ca39802cb6d3215ea0ef7214e3305412ba9cda6
