### ISSUE TITLE
Bug: Plain apricorn can be generated in vaults.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#77]
Guildmaster trail aways give the player a starting apricorn on floor 1, but this same apricorn can be generated inside vault. in theory this can prevent one from getting the said apricorn.
SEED: EDF4F05EA88D8C3C
Version: 5.0.11.0

**Comment by audinowho** [comment]
Fix in https://github.com/audinowho/PMDODump/commit/9436a6b0d9405cb6f45d5314e8b3ef0620297706
Incidentally, this phenomena also occurs with apples, leppas, apricorns, etc. that are spawned at a quota through the dungeon.  Those will still be left untouched by design.
