### ISSUE TITLE
PMDO Updater on Mac default installs to user's home directory

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#78]
## Issue
When double clicking an executable file on a Mac, that executable is run as if the user's home directory is the present working directory. This causes the PMDO Updater to install the game in the home directory instead of in the folder the updater is located in. The home directory is not easily visitable by a user who doesn't know about it, potentially causing some confusion when the updater claiming the game was successfully installed, but the game folder is nowhere to be seen.

## Steps to replicate
1. Download and unzip a fresh copy of PMDO Updater for Mac.
2. Make a new folder on the Desktop and move the Updater there.
3. Run the Updater by double-clicking it in Finder, and perform a normal install of the game.
4. Verify that there is no PMDO folder nor Updater.xml present in the new folder.
5. Visit the current user's home directory. Verify that the PMDO folder and Updater.xml were installed to this location instead.

## Proposed Solution
Have the updater change its working directory to the directory it is located in before performing an installation

**Comment by audinowho** [comment]
Fix in https://github.com/audinowho/PMDODump/commit/dbd89a48ed32cf4dec18251bc116b6c0c0394186
