### ISSUE TITLE
Item Sprite menu deletes wrong entry

### ISSUE THREAD

**Issue by Palikadude** [audinowho/PMDODump#79]
![image](https://user-images.githubusercontent.com/21061217/166391072-e0846873-86e1-4dea-822a-13c31916a703.png)

Looks like when you use a filter to look for specific item sprites and then try to delete one, it deletes the wrong item sprite instead. My guess is that it used whatever should normally be in that slot order wise if you hadn't used a filter, but I'm not really sure about that. It's definitely doing something wrong though.

**Comment by Palikadude** [comment]
![image](https://user-images.githubusercontent.com/21061217/166391330-9b3b510e-8d0d-44f4-899d-dba745d4b8ce.png)

Don't think it has to do with the filter, but it seems sometimes you have to go one above or something to get it to delete what you want (I want to delete chesto berry here as I used the wrong naming convention)

**Comment by audinowho** [comment]
Fix in https://github.com/RogueCollab/RogueEssence/commit/3b9fbc88b8e88470a4743885cb1c5d786b937861
