### ISSUE TITLE
Cliff camp sky is buged.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#81]
Entropy found out that probably is a bug on the scrolling of the sky, here's a screenshot.
![image](https://user-images.githubusercontent.com/6380147/167276475-97c18c55-4bfd-436c-b6d0-5fb028f90234.png)
entropy's screenshot:
![image](https://user-images.githubusercontent.com/6380147/167276488-23d2f96c-f96e-4bd9-b5d0-5d29ec869939.png)

**Comment by audinowho** [comment]
Fix as of https://github.com/audinowho/DumpAsset/commit/0d0c21f9848727eb07c98e33845991b8ce7ae49c
