### ISSUE TITLE
Entrances get stuck out of bounds when the map contracts in Map Editer

### ISSUE THREAD

**Issue by RaoKurai** [audinowho/PMDODump#82]
If you place an entrance(s) at the edge of a map while editing and then shrink the size of the map, they stay in place, even if that place is out of bounds after the map size change.  You can't delete them while they are out of bounds. Also if you try to save and test while the entrance is oob, the game crashes, so something to force them into the play space would be good to prevent those things.

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/commit/ef8dacbb368a904f257c6986b924b3d9049e9a69
