### ISSUE TITLE
Feature Request: Image Icons for the layer buttons in Map and Ground Editors

### ISSUE THREAD

**Issue by RaoKurai** [audinowho/PMDODump#84]
Specifically the 'D' 'M' '^' and 'v' buttons. To someone who doesn't already know what they do, they're a little vague, so images might convey what they do better. Not something high priority at all though.

**Comment by audinowho** [comment]
Added in https://github.com/RogueCollab/RogueEssence/commit/a78f7e016e5bfe0ab7c7d8e7cbc78155790a327c
