### ISSUE TITLE
Merge Button in Map and Ground Editors closes the game

### ISSUE THREAD

**Issue by RaoKurai** [audinowho/PMDODump#85]
Pressing the M button to merge layers instead closes the game window. Pressing it again closes the rest of the dev tools. Then you have to relaunch the game. Nothing lost or broken thankfully, but that makes the merge button unusable.

**Comment by audinowho** [comment]
This feature was just missing.
Added in https://github.com/RogueCollab/RogueEssence/commit/5a8dbda77d2cab3e5627f7a0f11c90cae6da2019
