### ISSUE TITLE
Supereffective sound effect/visual effect does not play with Battle Speed set to "Fast" or higher

### ISSUE THREAD

**Issue by Shitpost-Sunkern** [audinowho/PMDODump#87]

**Comment by Shitpost-Sunkern** [comment]
Follow up: some attacks (such as Crunch) lack hit effects entirely

**Comment by audinowho** [comment]
This is an intended effect of increasing the speed to Fast and Very Fast.  The effectiveness-hit vfx and sound take up a fraction of time separate from battle processes and are explicitly cut to make the battle faster.  The higher speeds assume the player knows what's coming effectiveness-wise, even when not shown the vfx for it.
