### ISSUE TITLE
Error in continue roguelocke in mods.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#88]
Loading any mod and them going in roguelocke/Continue (must have a non finished roguelock of main game) shows nothing in menu but pressing enter cause errors.
![image](https://user-images.githubusercontent.com/6380147/167317650-c6ddbe56-f077-414a-9c49-fa6443c3d032.png)

**Comment by audinowho** [comment]
fix in https://github.com/RogueCollab/RogueEssence/commit/45a62ce4f21f40da59108eb923c672e017918ef2
