### ISSUE TITLE
'Draw in Front' toggle is broken

### ISSUE THREAD

**Issue by RaoKurai** [audinowho/PMDODump#89]
In the map editors, the game appears to have some issue with the drawing in front toggle. Turning it on makes the game screen black and throws tons of errors. You have to reload the map to get a clear view again. It does this even on first opening of the editor with nothing changed or added.

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/commit/9e32d2cb18a5a47dced0ce3807d2131b3b7b8dce
