### ISSUE TITLE
X-specs in causing trouble in vision logic

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#93]
X-specs cause errors on entering dungeon while it is equiped, and using it while entering Replay test zone result in a crash.
[2022-05-15.zip](https://github.com/audinowho/PMDODump/files/8694867/2022-05-15.zip)
here's the log.

**Comment by audinowho** [comment]
Happens with all auto-stick items due to an item equip bug, fix in https://github.com/RogueCollab/RogueEssence/commit/ad3efd5bf125ef5b9d3bd462c4f2e6768644b385
