### ISSUE TITLE
Reaching level 100 cause error.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#94]
There's no event "level up" when you reach level 100, it just goes silently and cause a error in the game.
[2022-05-15.zip](https://github.com/audinowho/PMDODump/files/8694935/2022-05-15.zip)

**Comment by audinowho** [comment]
fix in https://github.com/RogueCollab/RogueEssence/commit/6b9b68d91481506a1c68a916b556b24893414f8d
